name: Auto Commit Every 30 Days

on:
  schedule:
   - cron: '0 0 1/30 * *'  # 每天的0点触发，每30天执行一次

jobs:
  auto-commit:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Commit changes
         run: |
           git config --global user.name 'Your Name'
           git config --global user.email 'your.email@example.com'
           git add .
           git commit -m "Automated commit every 30 days" || echo "No changes to commit"
           git push
