name: Auto Commit Every 30 Days

on:
  schedule:
   - cron: '0 0 1/30 * *'  # 每天的0点触发，每30天执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Add timestamp to README
        run: |
          echo "Last updated: $(date)" >> README.md
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Automated commit every 30 days" || echo "No changes to commit"
          git push
